version: "3.9"

services:
  api:
    build: ./api
    restart: always
    ports:
      - ${API_PORT}:8080
  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    volumes:
      - "./bdd/bdd_finale.sql:/docker-entrypoint-initdb.d/bdd_finale.sql"
    environment:
      MYSQL_ROOT_PASSWORD: "root"

  flaskserver:
    build: .
    restart: always
    ports:
      - ${APP_PORT}:3333
    volumes:
      - ${APP_SOURCES}:/app/appSources
    depends_on:
      - db

networks:
  demonet: