apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
  labels:
    app: info910
    role: front
spec:
  selector:
    matchLabels:
      app: info910
      role: front
  template:
    metadata:
      labels:
        app: info910
        role: front
    spec:
      containers:
      - name: api
        image: "ghcr.io/benjaminglt1/tpinfo910_api:latest"
        ports:
        - containerPort: 8080

---

apiVersion: v1
kind: Service
metadata:
  name: api
  labels:
    app: info910
    role: front
spec:
  selector:
    app: info910
    role: front
  type: ClusterIP
  ports:
  - port: 8080
    targetPort: 8080  