apiVersion: apps/v1
kind: Deployment
metadata:
  name: web
  labels:
    app: info910
    role: front
spec:
  selector:
    matchLabels:
      app: info910
      role: front
  template:
    metadata:
      labels:
        app: info910
        role: front
    spec:
      containers:
      - name: web
        image: "ghcr.io/benjaminglt1/tpinfo910_frontend:latest"
        ports:
        - containerPort: 3333

---

apiVersion: v1
kind: Service
metadata:
  name: web
  labels:
    app: info910
    role: front
spec:
  selector:
    app: info910
    role: front
  type: ClusterIP
  ports:
  - port: 3333
    targetPort: 3333  