-- MySQL Script generated by MySQL Workbench
-- Sun Nov  7 10:46:05 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema INFO910
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema INFO910
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `INFO910` DEFAULT CHARACTER SET utf8 ;
USE `INFO910` ;

-- -----------------------------------------------------
-- Table `INFO910`.`Utilisateur`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `INFO910`.`Utilisateur` (
  `Id` INT NOT NULL AUTO_INCREMENT,
  `Nom` VARCHAR(45) NOT NULL DEFAULT 'User',
  `Prenom` VARCHAR(45) NOT NULL DEFAULT 'User',
  `Telephone` VARCHAR(255) NOT NULL,
  `Email` VARCHAR(45) NOT NULL,
  `Login` VARCHAR(255) NOT NULL,
  `Password` VARCHAR(255) NOT NULL,
  `Carte` INT NULL,
  PRIMARY KEY (`Id`),
  UNIQUE INDEX `Id_UNIQUE` (`Id` ASC) ,
  UNIQUE INDEX `Login_UNIQUE` (`Login` ASC) )
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `INFO910`.`Editeur`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `INFO910`.`Editeur` (
  `Id` INT NOT NULL AUTO_INCREMENT,
  `Nom` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`Id`),
  UNIQUE INDEX `Id_UNIQUE` (`Id` ASC) ,
  UNIQUE INDEX `Nom_UNIQUE` (`Nom` ASC) )
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `INFO910`.`Jeu`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `INFO910`.`Jeu` (
  `Id` INT NOT NULL AUTO_INCREMENT,
  `Nom` VARCHAR(45) NOT NULL,
  `Description` VARCHAR(255) NOT NULL,
  `Prix` INT NOT NULL,
  `IdEditeur` INT NOT NULL,
  `IdCategorie` INT NOT NULL,
  PRIMARY KEY (`Id`),
  UNIQUE INDEX `Id_UNIQUE` (`Id` ASC) ,
  UNIQUE INDEX `Nom_UNIQUE` (`Nom` ASC) ,
  INDEX `editeur_idx` (`IdEditeur` ASC) ,
  CONSTRAINT `editeur_jeu`
    FOREIGN KEY (`IdEditeur`)
    REFERENCES `INFO910`.`Editeur` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `INFO910`.`Evaluation`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `INFO910`.`Evaluation` (
  `Id` INT NOT NULL AUTO_INCREMENT,
  `Note` VARCHAR(1) NOT NULL DEFAULT '5',
  `IdJeu` INT NOT NULL,
  `IdUtilisateur` INT NOT NULL,
  PRIMARY KEY (`Id`),
  UNIQUE INDEX `Id_UNIQUE` (`Id` ASC) ,
  INDEX `utilisateur_idx` (`IdUtilisateur` ASC) ,
  INDEX `jeu_idx` (`IdJeu` ASC) ,
  CONSTRAINT `utilisateur_evaluation`
    FOREIGN KEY (`IdUtilisateur`)
    REFERENCES `INFO910`.`Utilisateur` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `jeu_evaluation`
    FOREIGN KEY (`IdJeu`)
    REFERENCES `INFO910`.`Jeu` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `INFO910`.`Panier`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `INFO910`.`Panier` (
  `Id` INT NOT NULL AUTO_INCREMENT,
  `IdUtilisateur` INT NOT NULL,
  PRIMARY KEY (`Id`),
  UNIQUE INDEX `Id_UNIQUE` (`Id` ASC) ,
  INDEX `utilisateur_idx` (`IdUtilisateur` ASC) ,
  CONSTRAINT `utilisateur_panier`
    FOREIGN KEY (`IdUtilisateur`)
    REFERENCES `INFO910`.`Utilisateur` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `INFO910`.`Panier_Utilisateur`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `INFO910`.`Panier_Utilisateur` (
  `Id` INT NOT NULL AUTO_INCREMENT,
  `IdPanier` INT NOT NULL,
  `IdJeu` INT NOT NULL,
  PRIMARY KEY (`Id`),
  UNIQUE INDEX `Id_UNIQUE` (`Id` ASC) ,
  INDEX `jeu_idx` (`IdJeu` ASC) ,
  INDEX `panier_idx` (`IdPanier` ASC) ,
  CONSTRAINT `jeu_panier_utilisateur`
    FOREIGN KEY (`IdJeu`)
    REFERENCES `INFO910`.`Jeu` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `panier`
    FOREIGN KEY (`IdPanier`)
    REFERENCES `INFO910`.`Panier` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `INFO910`.`Jeux_Utilisateur`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `INFO910`.`Jeux_Utilisateur` (
  `IdUtilisateur` INT NOT NULL,
  `IdJeu` INT NOT NULL,
  INDEX `utilisateur_idx` (`IdUtilisateur` ASC) ,
  INDEX `jeu_idx` (`IdJeu` ASC) ,
  CONSTRAINT `utilisateur_jeux-utilisateur`
    FOREIGN KEY (`IdUtilisateur`)
    REFERENCES `INFO910`.`Utilisateur` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `jeu_jeux_utilisateur`
    FOREIGN KEY (`IdJeu`)
    REFERENCES `INFO910`.`Jeu` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `INFO910`.`Utilisateur_Cartes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `INFO910`.`Utilisateur_Cartes` (
  `IdUtilisateur` INT NOT NULL,
  `IdCarte` INT NOT NULL,
  INDEX `utilisateur_idx` (`IdUtilisateur` ASC) ,
  CONSTRAINT `utilisateur_utilisateur_cartes`
    FOREIGN KEY (`IdUtilisateur`)
    REFERENCES `INFO910`.`Utilisateur` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
